apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-clientes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: micro-clientes
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: micro-clientes
    spec:
      containers:
      - name: micro-clientes
        image: "gcr.io/smartleep-app/micro-clientes-deploy:latest"